In [1]:
print("Hello World!")

Hello World!

tiny.cc/amlclass1

### Step 1: Import Libraries

In [2]:
import pandas as pd

### Step 2: Load Dataset

In [3]:
dataset = pd.read_csv('Data.csv')
dataset.head()

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [13]:
features = ['Country', 'Age', 'Salary']
label = ['Purchased']

X = dataset[features]
y = dataset[label]

In [14]:
X

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

### Step 3: Missing values

In [15]:
X.iloc[:,1:3]

    Age   Salary
0  44.0  72000.0
1  27.0  48000.0
2  30.0  54000.0
3  38.0  61000.0
4  40.0      NaN
5  35.0  58000.0
6   NaN  52000.0
7  48.0  79000.0
8  50.0  83000.0
9  37.0  67000.0

In [16]:
import numpy as np
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

In [17]:
imputer = imputer.fit(X.iloc[:,1:3])

In [18]:
X.iloc[:,1:3] = imputer.transform(X.iloc[:,1:3])

c:\Users\user\anaconda3\lib\site-packages\pandas\core\indexing.py:1835: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)

In [19]:
X.iloc[:,1:3]

         Age        Salary
0  44.000000  72000.000000
1  27.000000  48000.000000
2  30.000000  54000.000000
3  38.000000  61000.000000
4  40.000000  63777.777778
5  35.000000  58000.000000
6  38.777778  52000.000000
7  48.000000  79000.000000
8  50.000000  83000.000000
9  37.000000  67000.000000

### Step 4: Encoding

In [20]:
from sklearn.preprocessing import LabelEncoder
labelEncoderX = LabelEncoder()
X.iloc[:, 0] = labelEncoderX.fit_transform(X.iloc[:,0])

c:\Users\user\anaconda3\lib\site-packages\pandas\core\indexing.py:1773: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)

In [21]:
labelEncoderY = LabelEncoder()
y = labelEncoderY.fit_transform(y)

c:\Users\user\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)

In [22]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

### Step 5: Train Test Split

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

### Step 6: Feature Scaling

In [26]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [27]:
X_train

array([[-0.90453403, -0.7529426 , -0.62603778],
       [-0.90453403,  1.00845381,  1.01304295],
       [-0.90453403,  1.79129666,  1.83258331],
       [ 0.30151134, -1.73149616, -1.09434656],
       [-0.90453403, -0.36152118,  0.42765698],
       [ 0.30151134,  0.22561096,  0.05040824],
       [ 1.50755672, -0.16581046, -0.27480619],
       [ 1.50755672, -0.01359102, -1.32850095]])